---
- hosts: webservers
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  
  tasks:
    - name: Update_the_packages
      apt:
        update_cache: yes


    - name: Installing the nginx, php7.4 and php7.4-fpm packages
      apt:
        name: ['nginx','php7.4','php7.4-fpm']
        state: latest
    
    - name: nginx configuration
      template:
        src: ./template/nginxdefault.conf
        dest: /etc/nginx/sites-available/default

    - name: index.php to the webservers
      copy:
        src: ./index.php
        dest: /var/www/html/index.php

    - name: Restarting the nginx
      service:
        name: nginx
        state: restarted



- hosts: all
  gather_facts: yes

- hosts: haproxy
  become: yes
  gather_facts: yes
  tasks:
    - name: installing haproxy
      apt:
        name: haproxy
        update_cache: yes
        state: latest

    - name: haproxy configuration to use as load balancer
      template:
        src: ./template/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: haproxy restart
      service:
        name: "haproxy"
        state: restarted